# Generated by Django 3.2.8 on 2021-10-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phoneotp',
            name='count',
        ),
        migrations.RemoveField(
            model_name='phoneotp',
            name='forgot',
        ),
        migrations.RemoveField(
            model_name='phoneotp',
            name='forgot_logged',
        ),
        migrations.RemoveField(
            model_name='phoneotp',
            name='logged',
        ),
        migrations.AlterField(
            model_name='phoneotp',
            name='phone',
            field=models.CharField(max_length=17, unique=True),
        ),
    ]
