# Generated by Django 3.2.8 on 2021-10-06 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_phoneotp_logged'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
