# Generated by Django 3.2.8 on 2021-10-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20211006_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneotp',
            name='phone',
            field=models.CharField(max_length=17),
        ),
    ]
