# Generated by Django 3.2.8 on 2021-10-06 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_phoneotp_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneotp',
            name='otp',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
