# Generated by Django 3.2.8 on 2021-10-07 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_phoneotp_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispatches',
            fields=[
                ('dis_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('dis_rep', models.CharField(max_length=100)),
                ('dis_wieght', models.IntegerField()),
                ('dis_dimen', models.CharField(max_length=20)),
                ('dis_packages', models.IntegerField()),
                ('commodity', models.CharField(max_length=200)),
                ('date_created', models.DateField()),
                ('dis_status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pickups',
            fields=[
                ('dis_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='pickup', serialize=False, to='api.dispatches', unique=True)),
                ('pick_location', models.CharField(max_length=200)),
                ('p_action', models.CharField(max_length=20)),
                ('p_arv_date', models.DateField()),
                ('p_dep_date', models.DateField()),
            ],
        ),
    ]
