# Generated by Django 3.2.8 on 2021-10-07 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_dispatches_pickups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickups',
            name='dis_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='pickup', serialize=False, to='api.dispatches'),
        ),
    ]
