# Generated by Django 3.2.8 on 2021-10-07 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20211007_0828'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pickups',
        ),
    ]
