# Generated by Django 3.2.8 on 2021-10-07 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_dispatches_dis_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deliveries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_location', models.CharField(max_length=200)),
                ('dev_action', models.CharField(max_length=20)),
                ('dev_arv_date', models.DateTimeField()),
                ('dev_dep_date', models.DateTimeField()),
                ('dis_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='api.dispatches')),
            ],
        ),
    ]
